# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Insights 2020
email: anna_rogers@uml.edu
description: >- # this means to ignore newlines until "baseurl:"
 Workshop on Insights from Negative Results in NLP
baseurl: "" # the subpath of your site, e.g. /blog
url: http://insights-workshop.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

include:
  - _pages
  - _pages/2021/
  - _pages/2020/

twitter:
  username: "annargrs"

# Build settings
markdown: kramdown
relative_permalinks: false
#theme: minima
#theme: jekyll-whiteglass
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

encoding: UTF-8
logo:  /assets/img/lemonade-logo.png
title_image: /assets/img/lemonade-white.png
show_downloads: false
google_analytics: UA-127096214-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
